### ISSUE TITLE
Error during put log events, timestamp parsing error

### ISSUE THREAD

**Issue by heretogo** [awslabs/cloudwatch-logs-centralize-logs#5]
I am having difficulty debugging this error. Basically the only modification I made to the code was to specify logStream and logGroup names. The permissions and triggers are okay but Lambda does not push the event to the log group.

```
2017-12-27T14:51:40.350Z	71fb13f0-eb15-11e7-83c6-0bf46de39d8f	Error during put log events: { InvalidParameterException: 1 validation error detected: Value null at 'logEvents.1.member.timestamp' failed to satisfy constraint: Member must not be null
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: '1 validation error detected: Value null at \'logEvents.1.member.timestamp\' failed to satisfy constraint: Member must not be null',
code: 'InvalidParameterException',
time: 2017-12-27T14:51:40.350Z,
requestId: '7257b336-eb15-11e7-bc19-ef76d7840c6a',
statusCode: 400,
retryable: false,
retryDelay: 9.592210548433599 } InvalidParameterException: 1 validation error detected: Value null at 'logEvents.1.member.timestamp' failed to satisfy constraint: Member must not be null
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
```

**Comment by vatshat** [comment]
I had the same error only to find that I had configured the wrong s3 bucket which didn't have my ELB access logs as my trigger for the lambda function which is why you get the InvalidParameterException error you're seeing. Make sure you've got the s3 bucket (and/or correct prefix) as your trigger.

**Comment by benhurley** [comment]
Also having the same issue, but I am definitely working out of the correct s3 bucket. Was anybody able to figure this out?

**Comment by heretogo** [comment]
Well in my case it was because I was trying to log IAM events. The script will only parse ELB logs. The solution was to enable CloudWatch Logs directly from CloudTrail. I didn't see the setting before.
